import { ZCOOL_KuaiLe } from "next/font/google";
import "./globals.css";

const zcoolKuaiLe = ZCOOL_KuaiLe({ weight: ["400"], subsets: ["latin"] });

export const metadata = {
  title: "Saviour-App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={zcoolKuaiLe.className}>
          {children}
      </body>
    </html>
  );
}
